version: '3'
name: example

services:

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/root/redis

  backend:
    build:
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/code
      - /srv/backend/public/media/:/srv/backend/public/media/
    command: uvicorn example.asgi:application --host 0.0.0.0 --port 8071 --reload
    ports:
      - "8071:8071"
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data: null
  redis-data: null
